version: '2.1'

volumes: 
  postgres-data: 
    driver: local

services:
  # Our PostgreSQL service:
  postgres:
    image: postgres:9.6.1
    ports:
      # We'll bind our host's port 5432 to postgres's port 5432, so we can use
      # our database IDEs with it:
      - 5432:5432
    volumes:
      # Mount the DB dumps folder into the container, to be able to create & access database dumps:
      - ./db/dumps:/db/dumps
      # Mount out tmp folder, we might want to have access to something there during development:
      - ./tmp:/tmp
      # Mount our 'restoredb' script:
      - ./bin/restoredb:/bin/restoredb:ro
      # Mount our 'dumpdb' script:
      - ./bin/dumpdb:/bin/dumpdb:ro
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: twaas
      POSTGRES_PASSWORD: 3x4mpl3

  # environment: &app_environment
  #   # The postgres database URL:
  #   DATABASE_URL: postgres://postgres:3x4mpl3@db.local:5432/example_development

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: madarauchiha/twaas-build
    working_dir: /app
    command: yarn start
    links:
      - postgres:db.local
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:3x4mpl3@db.local:5432/twaas